name: CI
on:
  workflow_dispatch:
    inputs:
      job_type:
        description: "Select the type of job"
        required: true
        default: "build-apk"
        type: choice
        options:
          - build-apk
          - build-server

jobs:
  build-apk:
    if: ${{ github.event.inputs.job_type == 'build-apk' }}
    runs-on: self-hosted
    steps:
      - name: Fetch & Copy
        run: sh ./start.sh
        
      - name: Run local script
        run: source ./env-prepare.sh

      - name: Run local script
        run: sh ./client/build.sh
        
  build-server:
    if: ${{ github.event.inputs.job_type == 'build-server' }}
    runs-on: self-hosted
    steps:
      - name: Fetch & Copy
        run: sh ./start.sh
        
      - name: Run local script
        run: source ./env-prepare.sh

      - name: build server
        run: sh ./server/build.sh

      - name: container server
        run: sh ./server/container.sh
